---
- name: Uninstall Multiple Software
  hosts: ubuntu
  vars:
    software_lists:
      - nginx
      - default-jre
      - python3.10
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Uninstall software
      apt:
        name: "{{ item }}"
        state: absent
      loop: "{{ software_lists }}"
